### ISSUE TITLE
gui_application - main.py

### ISSUE THREAD

**Issue by michaelsunglee** [DarkmatterVale/regex4dummies#9]
Running main.py in the gui_application directory doesn't seem to launch.

**Comment by DarkmatterVale** [comment]
Hi Michael,

Yes. I am still developing the GUI. Currently, I am in the design stage and am planning on using either Kivy or TKinter to implement the GUI.

The first version of the GUI should be completed within a week or two. Sorry for the inconvenience!

**Comment by DarkmatterVale** [comment]
The GUI should now work since the most recent update. Does it work if you update to the latest version from pip?
